- hosts: all
  vars_files:
    - vars/users.yml
  roles:
    - {role: Ansibles.generic-users, tags: ['users']}
  tasks:
    - name: updates apt cache
      apt: update_cache=yes
      tags: ['apt_update']

    - name: upgrade server
      apt: upgrade=full
      tags: ['apt']

    - name: install unattended-upgrades
      apt: name=unattended-upgrades state=present
      tags: ['install-unattended-upgrades']

    - name: run unattended-upgrades
      command: unattended-upgrades
      tags: ['run-unattended-upgrades']

    - name: Copy sudoers file for safety
      command: cp -f /etc/sudoers /etc/sudoers.tmp
      tags: ['sudo']

    - name: Create sudoers file backup
      command: cp -f /etc/sudoers /etc/sudoers.bak
      tags: ['sudo']

    - name: give ckan_dev group sudo access
      lineinfile: dest=/etc/sudoers.tmp state=present regexp='^%ckan_dev' line='%ckan_dev ALL=(ALL) NOPASSWD:ALL'
      tags: ['sudo']

    - name: Final sudoers file check
      shell: visudo -q -c -f /etc/sudoers.tmp && cp -f /etc/sudoers.tmp /etc/sudoers
      tags: ['sudo']
